
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author PRIYADHARSHINI
 */
public class AboutYou extends javax.swing.JFrame {

    /**
     * Creates new form AboutYou
     */
    public AboutYou() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        label3 = new java.awt.Label();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label1.setFont(new java.awt.Font("Algerian", 0, 36)); // NOI18N
        label1.setText("ABOUT YOU");

        label2.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        label2.setText("ENTER YOUR FIRST LETTER");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jButton1.setText("GO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        label3.setAlignment(java.awt.Label.CENTER);
        label3.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        label3.setText("PROSPERITY IS THE ONLY REASON FOR YOU TO SURVIE! CHEERS TO LIVING");

        jButton2.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jButton2.setText("HOME");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(279, 279, 279))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(36, 36, 36)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(353, 353, 353))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(337, 337, 337))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(61, 61, 61)
                .addComponent(jButton1)
                .addGap(43, 43, 43)
                .addComponent(jButton2)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String a;
        a=jTextField1.getText();
        if(a.length()==0)
            JOptionPane.showMessageDialog(rootPane,"Please enter a valid first letter");
        else 
        {
            char ch;
            ch=a.toLowerCase().charAt(0);
            switch(ch)
            {
                case 'a':
                    JOptionPane.showMessageDialog(rootPane,"There is a true and sincere friendship between your and your friends." );
                    break;
                case 'b':
                    JOptionPane.showMessageDialog(rootPane,"Smiling often can make you look and feel younger." );
                    break;
                case 'c':
                    JOptionPane.showMessageDialog(rootPane,"You find beauty in ordinary things, do not lose this ability." );
                    break;
                case 'd':
                    JOptionPane.showMessageDialog(rootPane,"Someone is speaking well of you." );
                    break;
                case 'e':
                    JOptionPane.showMessageDialog(rootPane,"Ideas are like children; there are none so wonderful as your own." );
                    break;
                case 'f':
                    JOptionPane.showMessageDialog(rootPane,"The time is right to make new friends." );
                    break;
                case 'g':
                    JOptionPane.showMessageDialog(rootPane,"It takes more than good memory to have good memories." );
                    break;
                case 'h':
                    JOptionPane.showMessageDialog(rootPane,"You will inherit some money or a small piece of land." );
                    break;
                case 'i':
                    JOptionPane.showMessageDialog(rootPane,"A thrilling time is in your immediate future" );
                    break;
                case 'j':
                    JOptionPane.showMessageDialog(rootPane,"Your life will be happy and peaceful" );
                    break;
                case 'k':
                    JOptionPane.showMessageDialog(rootPane,"Your blessing is no more than being safe and sound for the whole lifetime." );
                    break;
                case 'l':
                    JOptionPane.showMessageDialog(rootPane,"A friend is a present you give yourself." );
                    break;
                case 'm':
                    JOptionPane.showMessageDialog(rootPane,"Plan for many pleasures ahead." );
                    break;
                case 'n':
                    JOptionPane.showMessageDialog(rootPane,"A member of your family will soon do something that will make you proud." );
                    break;
                case 'o':
                    JOptionPane.showMessageDialog(rootPane,"The joyfulness of a man prolongeth his days." );
                    break;
                case 'p':
                    JOptionPane.showMessageDialog(rootPane,"A quiet evening with friends is the best tonic for a long day" );
                    break;
                case 'q':
                    JOptionPane.showMessageDialog(rootPane,"Your everlasting patience will be rewarded sooner or later." );
                    break;
                case 'r':
                    JOptionPane.showMessageDialog(rootPane,"A single kind word will keep one warm for years." );
                    break;
                case 's':
                    JOptionPane.showMessageDialog(rootPane,"Make two grins grow where there was only a grouch before" );
                    break;
                case 't':
                    JOptionPane.showMessageDialog(rootPane,"Anger begins with folly, and ends with regret." );
                    break;
                case 'u':
                    JOptionPane.showMessageDialog(rootPane,"Something you lost will soon turn up." );
                    break;
                case 'v':
                    JOptionPane.showMessageDialog(rootPane,"Generosity and perfection are your everlasting goals." );
                    break;
                case 'w':
                    JOptionPane.showMessageDialog(rootPane,"Your heart is pure, and your mind clear, and your soul devout." );
                    break;
                case 'x':
                    JOptionPane.showMessageDialog(rootPane,"Happy news is on its way to you." );
                    break;
                case 'y':
                    JOptionPane.showMessageDialog(rootPane,"Excitement and intrigue follow you closely wherever you go!" );
                    break;
                case 'z':
                    JOptionPane.showMessageDialog(rootPane,"A pleasant surprise is in store for you." );
                    break;
        }    
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
        new Home().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AboutYou.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AboutYou.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AboutYou.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AboutYou.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AboutYou().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JTextField jTextField1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    // End of variables declaration//GEN-END:variables
}
